### ISSUE TITLE
PHP : echo with comma?

### ISSUE THREAD

**Issue by TonyLight** [nuhmanpk/SuperLogger#7]
Hey, 

I think there's an error in the use of _echo_ for PHP. Indeed, you're using a comma when it should be a dot for concatenation.

The generated code is:
`echo ("🎃 ~ Home.php:90 -> $data: ",  $data);`

It should be:
`echo "🎃 ~ Home.php:90 -> \$data: " . print_r($data, true);`

**Comment by nuhmanpk** [comment]
@TonyLight Thanks. Will fix this ASAP

**Comment by nuhmanpk** [comment]
Fixed on version 0.1.0
